services:
  api:
    container_name: back-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - BOT_TOKEN=6001994688:AAFGfTXD4rscEW9F3kRwLNIi1ViGzV86gA8
      - WEB_APP_URL=https://olymp-bot-official.com/
    ports:
      - 5000:5000
  web:
    depends_on: [api]
    container_name: front-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
